### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by ColtonMcInroy** [totaljs/flow#81]
A couple of things I have noticed when using the dark theme. Drop downs connected to a text field and buttons do not colour correctly. Take a look at the Switch settings component.

![image](https://user-images.githubusercontent.com/121206906/212980533-8d067566-0a32-4368-a3f4-d7c5a38a6475.png)

Also the area for the Print JSON component does not appear to obey the theme. I know I saw it use the correct colours to match the theme at some point, but currently it appears to only show as white. This could be due to a recent update.
If I recall correctly, adding a new Print JSON component would result in the area showing unmatched theme colours but closing the tab and re-opening the flow would make it show up correctly. This is the behaviour I was noticing previously, but I have been keeping up with git pulls and currently it always appears the area is theme with the light theme.

**Comment by ColtonMcInroy** [comment]
Here is the Print JSON component showing up a white in the dark theme...

![image](https://user-images.githubusercontent.com/121206906/212982135-3ae27f35-ae50-4079-9d16-acda36f2c4fc.png)

**Comment by petersirka** [comment]
UI components have been fixed https://github.com/totaljs/flow/commit/d8e647c9d70875e2caa43bc92ca7400ff62cd9d3
We will look at the components.

**Comment by ColtonMcInroy** [comment]
The Add button for the switch component still appears to have an issue...

![image](https://user-images.githubusercontent.com/121206906/214183765-b2fe3e30-99d1-408a-b3e3-93120f8855d5.png)

**Comment by petersirka** [comment]
@TerezzaB Can you fix it? I still see silver borders in dark mode.

**Comment by TerezzaB** [comment]
@ColtonMcInroy it's fixed https://github.com/totaljs/flowstreamcomponents/commit/de5901ceaf1f7a6ae1222b8f28fdedadae60672d
